import { ArrowRight, BarChart3, Bot, Brain, CheckCircle2, Database, Globe, Layers3, LineChart, MessageSquare, Palette, Search, ShieldCheck, Sparkles, Target, Workflow } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import CTA from "@/components/home/cta/CTA";

const serviceGroups = [
  { eyebrow: "Growth Engine", title: "Lead generation, Google Ads and Meta Ads built as one system.", description: "We build full-funnel acquisition systems for businesses that need predictable demand, not random campaign activity. From offer strategy and landing pages to Google Ads, Meta Ads, tracking and lead qualification, everything is connected around one goal: better leads at a lower cost.", icon: BarChart3, color: "#FFCA00", items: ["Google Search, Performance Max and YouTube campaigns", "Meta Ads for lead generation, retargeting and demand creation", "Landing pages designed around conversion, speed and trust", "CRM-ready lead capture, tagging and follow-up workflows", "Analytics, attribution and weekly optimisation decisions", "Reputation-led campaigns for clinics, restaurants and service brands"], proof: undefined },
  { eyebrow: "AI Operations", title: "AI chat, automation and workflows that make your business faster.", description: "We turn repetitive conversations, lead handling and internal tasks into automated workflows. The goal is not to add random AI features. The goal is to make your team respond faster, qualify better, follow up consistently and spend less time on manual work.", icon: Brain, color: "#2A7BFF", items: ["AI chatbots for websites, WhatsApp and customer support", "Lead qualification flows that route serious buyers faster", "CRM automations for follow-ups, reminders and pipeline movement", "Internal workflow automation for sales, operations and admin teams", "Knowledge-base assistants trained around your services and FAQs", "Human handoff logic so automation never feels cold or careless"], proof: "Useful for service businesses, clinics, education brands, restaurants, real estate and finance teams that handle high-intent inquiries." },
  { eyebrow: "Digital Product", title: "Websites, web apps and software that feel premium and perform.", description: "We design and engineer digital products that are fast, clean and built around real business use cases. Whether you need a marketing website, booking flow, internal dashboard, SaaS-style product or custom web application, we focus on clarity, performance and long-term scalability.", icon: Globe, color: "#071A63", items: ["High-performance websites built with modern frameworks", "Custom web apps, portals, dashboards and admin systems", "Booking, payment, form and CRM integrations", "AI-powered product features and internal tools", "Mobile-responsive UI with premium visual polish", "Deployment, hosting, analytics and ongoing improvement"], proof: undefined },
  { eyebrow: "Brand Intelligence", title: "Content, creative and reputation systems that build authority.", description: "We help brands look credible before a customer ever speaks to them. That means stronger positioning, better creative, sharper content, improved review presence and digital assets that make your business feel established, trusted and ready to buy from.", icon: Palette, color: "#FFCA00", items: ["Brand positioning, identity direction and message clarity", "Social content systems for awareness, trust and demand", "Ad creatives, landing page visuals and campaign assets", "Review generation and online reputation improvement", "Authority-building content for search and social channels", "Creative strategy that supports sales, not vanity posting"], proof: "Strong fit for hospitality, healthcare, finance, education, ecommerce and local service businesses." },
];
const ecosystemSteps = [{ title: "Strategy", description: "We map the offer, audience, buying journey and growth bottlenecks before touching campaigns or code.", icon: Target }, { title: "Build", description: "We create the website, automations, ads, content and tracking needed to make the system work.", icon: Layers3 }, { title: "Launch", description: "We connect the moving parts, test the experience and launch with clean data from day one.", icon: Sparkles }, { title: "Improve", description: "We review performance, remove friction and keep improving the system as your business grows.", icon: LineChart }];
const clients = ["Z House", "FlexPoint", "Upzone", "Zed's Kitchen", "Fatima Dental Hospital", "Terteeb", "Kamn Capital", "PayG Aligners", "Reliable Accounting Solutions", "Silkoze", "Integral Psychiatric Care", "Bubble Burst Game"];
const stack = [{ label: "Google Ads", icon: Search }, { label: "Meta Ads", icon: Target }, { label: "AI Chatbots", icon: MessageSquare }, { label: "Automation", icon: Workflow }, { label: "Web Apps", icon: Database }, { label: "Brand Content", icon: Sparkles }];

export default function ServicesPage() {
  return <><Navbar /><main className="overflow-hidden bg-[#F8F9FC]">
    <section id="home" className="relative px-6 pb-20 pt-40 md:pb-28 md:pt-44">
      <div className="absolute left-1/2 top-20 h-[520px] w-[520px] -translate-x-1/2 rounded-full bg-blue-200/25 blur-[120px]" /><div className="absolute -left-20 top-60 h-80 w-80 rounded-full bg-[#FFCA00]/15 blur-[110px]" /><div className="absolute -right-20 top-72 h-80 w-80 rounded-full bg-[#071A63]/10 blur-[110px]" />
      <div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-5xl text-center"><div className="mx-auto inline-flex rounded-full border border-slate-200 bg-white/80 px-5 py-2 shadow-sm backdrop-blur-xl"><span className="text-xs font-bold uppercase tracking-[0.32em] text-[#071A63]">Raptivio Growth Services</span></div><h1 className="mt-8 font-manrope text-5xl font-bold leading-[1.02] tracking-[-0.05em] text-[#071A63] md:text-7xl">One intelligent ecosystem for growth, software and AI.</h1><p className="mx-auto mt-7 max-w-3xl text-lg leading-8 text-slate-600 md:text-xl md:leading-9">Raptivio helps ambitious businesses connect marketing, websites, automation, AI and content into one focused system. Not scattered services. Not disconnected campaigns. A smarter operating layer for growth.</p><div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row"><a href="/contact" className="inline-flex items-center gap-3 rounded-full bg-[#071A63] px-8 py-4 text-base font-semibold text-white shadow-xl transition hover:-translate-y-1 hover:bg-[#102d8f]">Start a Growth Plan <ArrowRight size={20} /></a><a href="#services" className="inline-flex items-center gap-3 rounded-full border border-slate-200 bg-white px-8 py-4 text-base font-semibold text-[#071A63] shadow-sm transition hover:-translate-y-1 hover:border-[#FFCA00]">Explore Services</a></div></div>
      <div className="mt-16 grid gap-4 md:grid-cols-3 lg:grid-cols-6">{stack.map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-[24px] border border-slate-200 bg-white/80 p-5 text-center shadow-sm backdrop-blur-xl"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#071A63] text-white"><Icon size={21} /></div><p className="mt-4 text-sm font-semibold text-[#071A63]">{item.label}</p></div>; })}</div></div>
    </section>
    <section id="services" className="px-6 py-12 md:py-20"><div className="mx-auto max-w-7xl"><div className="mb-12 max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.32em] text-[#FFCA00]">What We Build</p><h2 className="mt-4 font-manrope text-4xl font-bold tracking-[-0.04em] text-[#071A63] md:text-6xl">Services that work better when they work together.</h2></div><div className="space-y-7">{serviceGroups.map((service, index) => { const Icon = service.icon; return <article key={service.title} className="group relative overflow-hidden rounded-[34px] border border-slate-200 bg-white p-7 shadow-sm transition duration-500 hover:-translate-y-1 hover:shadow-2xl md:p-10"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full blur-[120px]" style={{ backgroundColor: `${service.color}22` }} /><div className="absolute -bottom-28 -left-20 h-72 w-72 rounded-full bg-[#071A63]/10 blur-[120px]" /><div className="relative z-10 grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-start"><div><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-[#FFCA00] to-[#071A63] text-white shadow-lg"><Icon size={30} /></div><div><p className="text-xs font-bold uppercase tracking-[0.32em] text-slate-400">0{index + 1}</p><p className="mt-1 text-sm font-bold uppercase tracking-[0.25em] text-[#071A63]">{service.eyebrow}</p></div></div><h3 className="mt-8 font-manrope text-3xl font-bold leading-tight tracking-[-0.03em] text-[#071A63] md:text-5xl">{service.title}</h3><p className="mt-6 text-lg leading-8 text-slate-600">{service.description}</p>{service.proof && <p className="mt-6 rounded-2xl border border-[#FFCA00]/25 bg-[#FFCA00]/10 p-4 text-sm leading-7 text-[#071A63]">{service.proof}</p>}</div><div className="rounded-[28px] border border-slate-100 bg-[#F8F9FC] p-5 md:p-7"><div className="grid gap-3">{service.items.map((item) => <div key={item} className="flex gap-3 rounded-2xl bg-white p-4 shadow-sm"><CheckCircle2 size={20} className="mt-0.5 flex-shrink-0 text-[#071A63]" /><span className="text-sm font-medium leading-6 text-slate-700">{item}</span></div>)}</div></div></div></article>; })}</div></div></section>
    <section className="px-6 py-16 md:py-24"><div className="mx-auto max-w-7xl rounded-[36px] bg-[#071A63] p-8 text-white shadow-2xl md:p-12"><div className="grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.32em] text-[#FFCA00]">How Raptivio Works</p><h2 className="mt-5 font-manrope text-4xl font-bold tracking-[-0.04em] md:text-6xl">We build the system around how your business actually grows.</h2><p className="mt-6 text-lg leading-8 text-white/70">Every business has a different growth bottleneck. Some need leads. Some need a better website. Some need automation. Some need stronger trust and content. We connect the right pieces instead of forcing every client into the same package.</p></div><div className="grid gap-4 md:grid-cols-2">{ecosystemSteps.map((step) => { const Icon = step.icon; return <div key={step.title} className="rounded-[26px] border border-white/10 bg-white/10 p-6 backdrop-blur-xl"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#FFCA00] text-[#071A63]"><Icon size={22} /></div><h3 className="mt-5 text-xl font-bold">{step.title}</h3><p className="mt-3 text-sm leading-7 text-white/65">{step.description}</p></div>; })}</div></div></div></section>
    <section className="px-6 py-14 md:py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.32em] text-[#FFCA00]">Client Context</p><h2 className="mt-4 font-manrope text-4xl font-bold tracking-[-0.04em] text-[#071A63] md:text-5xl">Built for real businesses, not imaginary use cases.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Our work sits across hospitality, healthcare, finance, professional services, ecommerce, software and local service brands. The page is about what we can build, but the thinking comes from practical client environments.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{clients.map((client) => <div key={client} className="rounded-2xl border border-slate-200 bg-white px-4 py-5 text-center text-sm font-semibold text-[#071A63] shadow-sm">{client}</div>)}</div></div></div></section>
    <section className="px-6 py-16 md:py-24"><div className="mx-auto grid max-w-7xl gap-6 md:grid-cols-3">{[[ShieldCheck, "Premium without being slow", "We keep the work polished, but practical. Fast decisions, clean execution and clear priorities."], [Bot, "AI where it actually helps", "We use AI to improve speed, response quality, workflow and decision-making, not just to make the website sound modern."], [LineChart, "Built around outcomes", "Leads, trust, conversion, speed and operational clarity are the real metrics behind the services we offer."]].map(([Icon, title, copy]) => { const CardIcon = Icon as typeof ShieldCheck; return <div key={title as string} className="rounded-[30px] border border-slate-200 bg-white p-8 shadow-sm"><CardIcon size={34} className="text-[#071A63]" /><h3 className="mt-6 text-2xl font-bold text-[#071A63]">{title as string}</h3><p className="mt-4 leading-7 text-slate-600">{copy as string}</p></div>; })}</div></section>
    <CTA />
  </main></>;
}
